#!/usr/local/bin/python2.7

import os
import argparse

parser = argparse.ArgumentParser(description='Display frames from high-speed Phantom camera videos.')
parser.add_argument('shot', type=str, nargs='?',
                    help='shot number')
#parser.add_argument('-p', '--play', action='store_true',
#                    help='play video with no user control')
args = parser.parse_args()

good_python = '/usr/local/bin/python2.7'
view_path = os.path.dirname(os.path.realpath(__file__)) + '/view.py'

if args.shot:
    os.system('{python} -i {view} {shot}'.format(python=good_python, view=view_path, shot=args.shot))
else:
    os.system('{python} -i {view}'.format(python=good_python, view=view_path))

